---
- name: Run Tomcat inside Docker
  hosts: all
  become: true  
  tasks:
    - name: Docker login
      shell: 'docker login docker.com -u {{ docker_user }} -p {{ docker_pass }}'
    - name: See running containers
      shell: docker ps --filter name=tomcat -q
      register: run_list
    - name: See all containers
      shell: docker ps --filter name=tomcat -aq
      register: stop_list
    - set_fact:
        diff: '{{ (stop_list.stdout_lines | difference(run_list.stdout_lines)) | length }}'
        run: '{{ run_list.stdout_lines | length }}'
    - name: Remove previous containers
      shell: docker stop tomcat && docker rm tomcat
      when: diff | int != 0
    - name: Run Tomcat container
      shell: 'docker run -d -p 8080:8080 danpil/nxbootcamp:krylova.valeria.healthcheck_service-{{ version }}'
      when: diff | int != 0 or run | int == 0

